# Generated by Django 4.2.16 on 2025-01-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_cart_cartitem_cart_products_cart_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
